site_name: EarthSystem


# Repository
repo_name: EarthSystem
repo_url:https://github.com/Jakopf4/EarthSystem.git
edit_uri: ""
# Copyright
copyright: Jakopf4

docs_dir: "docs/sources"

plugins:
  - search

theme:
  name: 'readthedocs'
  custom_dir: 'docs'
  palette:
    primary: 'white'
  logo: ''
  favicon: ''
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - instant
nav:

